### ISSUE TITLE
cfde-submit raises Validation Error without showing what didn't validate

### ISSUE THREAD

**Issue by NickolausDS** [nih-cfde/submission-workflow#59]
This is @ACharbonneau's error report, let me know if I missed anything!

When submitting a new dataset using `cfde-submit run LINCS-metadata/c2m2_level1/ --dcc-id cfde_registry_dcc:lincs`, no useful validation messages were produced. Instead, cfde-submit showed this:

```
DEBUG:cfde_submit.validation:BDBag created at '/mnt/ufs18/home-126/charbo24/cfde/LINCS-metadata/c2m2_level1_e831f600893976082613d564cedbfca7f7836493'
DEBUG:cfde_submit.validation:Archiving BDBag at '/mnt/ufs18/home-126/charbo24/cfde/LINCS-metadata/c2m2_level1_e831f600893976082613d564cedbfca7f7836493' using 'zip'
DEBUG:cfde_submit.validation:BDBag archived to file '/mnt/ufs18/home-126/charbo24/cfde/LINCS-metadata/c2m2_level1_e831f600893976082613d564cedbfca7f7836493.zip'
DEBUG:cfde_submit.validation:Removing old directory '/mnt/ufs18/home-126/charbo24/cfde/LINCS-metadata/c2m2_level1_e831f600893976082613d564cedbfca7f7836493'
DEBUG:cfde_submit.validation:Validating TableSchema in BDBag '/mnt/ufs18/home-126/charbo24/cfde/LINCS-metadata/c2m2_level1_e831f600893976082613d564cedbfca7f7836493.zip'
ERROR:cfde_submit.main:TableSchema invalid due to the following errors:
Traceback (most recent call last):
  File "/mnt/ufs18/home-126/charbo24/cfde/cfde_venv/lib/python3.6/site-packages/cfde_submit/main.py", line 110, in run
    force_http=force_http, **bag_kwargs)
  File "/mnt/ufs18/home-126/charbo24/cfde/cfde_venv/lib/python3.6/site-packages/cfde_submit/client.py", line 304, in start_deriva_flow
    handle_git_repos=handle_git_repos, bdbag_kwargs=kwargs
  File "/mnt/ufs18/home-126/charbo24/cfde/cfde_venv/lib/python3.6/site-packages/cfde_submit/validation.py", line 215, in validate_user_submission
    "\n{}\n".format(validation_res["error"]))
cfde_submit.exc.ValidationException: TableSchema invalid due to the following errors:
Error while starting Flow: ValidationException('TableSchema invalid due to the following errors: \n\n',)
```

The dataset used was here: https://github.com/nih-cfde/LINCS-metadata/tree/main/c2m2_level1 using commit e831f600893976082613d564cedbfca7f7836493

**Comment by NickolausDS** [comment]
I tried to reproduce, but didn't quite get the same result. I used the latest version of cfde-submit, which is a different version. That may mean this bug is fixed, although I think the error reporting needs work:

```
(cfde-submit) nick@Firefly cfde-submit % cfde-submit run dataset-testing/LINCS-metadata/c2m2_level1/ --dcc-id cfde_registry_dcc:lincs
Would you like to save cfde_registry_dcc:lincs as your default DCC ID (instead of"cfde_registry_dcc:kidsfirst"?) (y/n)? > y
Running on service 'dev'
Submit datapackage '' using cfde_registry_dcc:lincs? (y/n)? > y
TableSchema invalid due to the following errors: 
Field "size_in_bytes" can't cast value "203229.0" for type "integer" with format "default"
Field "uncompressed_size_in_bytes" can't cast value "533867.0" for type "integer" with format "default"
Traceback (most recent call last):
  File "/Users/nick/anaconda3/envs/cfde-submit/lib/python3.9/site-packages/cfde_submit-0.1.8-py3.9.egg/cfde_submit/main.py", line 99, in run
    start_res = cfde.start_deriva_flow(data_path, dcc_id=dcc_id, catalog_id=catalog,
  File "/Users/nick/anaconda3/envs/cfde-submit/lib/python3.9/site-packages/cfde_submit-0.1.8-py3.9.egg/cfde_submit/client.py", line 307, in start_deriva_flow
    data_path = validation.validate_user_submission(
  File "/Users/nick/anaconda3/envs/cfde-submit/lib/python3.9/site-packages/cfde_submit-0.1.8-py3.9.egg/cfde_submit/validation.py", line 214, in validate_user_submission
    raise exc.ValidationException("TableSchema invalid due to the following errors: "
cfde_submit.exc.ValidationException: TableSchema invalid due to the following errors: 
Field "size_in_bytes" can't cast value "203229.0" for type "integer" with format "default"
Field "uncompressed_size_in_bytes" can't cast value "533867.0" for type "integer" with format "default"

Error while starting Flow: ValidationException('TableSchema invalid due to the following errors: \nField "size_in_bytes" can\'t cast value "203229.0" for type "integer" with format "default"\nField "uncompressed_size_in_bytes" can\'t cast value "533867.0" for type "integer" with format "default"\n')
```

Ideally, the cfde-submit client would catch the validation error and print only the validation errors. Printing the ValidationException string itself may actually be quite a nice error message.

**Comment by ACharbonneau** [comment]
as an aside, that message helped! My flow still failed, but it failed further along after I fixed the integer issue.

**Comment by NickolausDS** [comment]
There's a new fix in https://github.com/nih-cfde/cfde-submit/pull/24 which makes that error message pretty and readable. It will be out in the next release!

**Comment by NickolausDS** [comment]
It should also prevent you from running flows unless validation passes on the cfde-submit client first.
